#### Eksik Veri Analizi

In [16]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,6,np.nan,7,1,np.nan,9,15])
V2 = np.array([7,np.nan,5,8,12,np.nan,np.nan,2,3])
V3 = np.array([np.nan,12,5,6,14,7,np.nan,2,31])
df = pd.DataFrame(
    {"V1":V1,
     "V2":V2,
     "V3":V3})
df

     V1    V2    V3
0   1.0   7.0   NaN
1   3.0   NaN  12.0
2   6.0   5.0   5.0
3   NaN   8.0   6.0
4   7.0  12.0  14.0
5   1.0   NaN   7.0
6   NaN   NaN   NaN
7   9.0   2.0   2.0
8  15.0   3.0  31.0

#### Eksik Değerlere Erişmek

In [2]:
#boş değerlerin gösterilmesi
df.isnull().sum()

V1    2
V2    3
V3    2
dtype: int64

In [3]:
#boş olmayan değerlere erişim
df.notnull().sum()

V1    7
V2    6
V3    7
dtype: int64

In [4]:
#toplam boş değer bilgisine erişim
df.isnull().sum().sum()

np.int64(7)

In [5]:
df.isnull()

      V1     V2     V3
0  False  False   True
1  False   True  False
2  False  False  False
3   True  False  False
4  False  False  False
5  False   True  False
6   True   True   True
7  False  False  False
8  False  False  False

In [19]:
# en az bir değeri NaN olan bütün gözlem birimlerinin getirilmesi
df[df.isnull().any(axis = 1)]

    V1   V2    V3
0  1.0  7.0   NaN
1  3.0  NaN  12.0
3  NaN  8.0   6.0
5  1.0  NaN   7.0
6  NaN  NaN   NaN

In [20]:
# bütün değerleri dolu olan gözlem birimlerinin getirilmesi
df[df.notnull().all(axis = 1)]

     V1    V2    V3
2   6.0   5.0   5.0
4   7.0  12.0  14.0
7   9.0   2.0   2.0
8  15.0   3.0  31.0

In [8]:
#hiçbir şey bilmesek bile alternatif gösterim
df[df["V1"].notnull() & df["V2"].notnull() & df["V3"].notnull()]

     V1    V2    V3
2   6.0   5.0   5.0
4   7.0  12.0  14.0
7   9.0   2.0   2.0
8  15.0   3.0  31.0

#### Eksik Değerlerin Silinmesi

In [9]:
df.dropna(inplace = False)
#kalıcı olarak silme
#df.dropna(inplace = True)

     V1    V2    V3
2   6.0   5.0   5.0
4   7.0  12.0  14.0
7   9.0   2.0   2.0
8  15.0   3.0  31.0

In [10]:
df

     V1    V2    V3
0   1.0   7.0   NaN
1   3.0   NaN  12.0
2   6.0   5.0   5.0
3   NaN   8.0   6.0
4   7.0  12.0  14.0
5   1.0   NaN   7.0
6   NaN   NaN   NaN
7   9.0   2.0   2.0
8  15.0   3.0  31.0

#### Basit Değer Atama

In [12]:
df["V1"]

0     1.0
1     3.0
2     6.0
3     NaN
4     7.0
5     1.0
6     NaN
7     9.0
8    15.0
Name: V1, dtype: float64

In [13]:
df["V1"].mean()

np.float64(6.0)

In [14]:
df["V1"].fillna(df["V1"].mean())

0     1.0
1     3.0
2     6.0
3     6.0
4     7.0
5     1.0
6     6.0
7     9.0
8    15.0
Name: V1, dtype: float64

In [15]:
df["V2"].fillna(0)

0     7.0
1     0.0
2     5.0
3     8.0
4    12.0
5     0.0
6     0.0
7     2.0
8     3.0
Name: V2, dtype: float64

*Onlarca değişkene sahip bir veri setinde böyle çalışmak anlamsız. Bu işlemleri otomatize etmemiz gerek. Burada fonksiyonel programlama devreye giriyor.*

In [17]:
#boş değerlere otomatik atama işlemi

In [18]:
df.apply(lambda x: x.fillna(x.mean()), axis = 0)

     V1         V2    V3
0   1.0   7.000000  11.0
1   3.0   6.166667  12.0
2   6.0   5.000000   5.0
3   6.0   8.000000   6.0
4   7.0  12.000000  14.0
5   1.0   6.166667   7.0
6   6.0   6.166667  11.0
7   9.0   2.000000   2.0
8  15.0   3.000000  31.0

*apply() fonksiyonunun değişkenler üzerinde çalıştığını hatırlayalım. x, burada değişkenleri temsil ediyor. axis = 0 parametresi de her bir değişken için satır satır dolaşmamız gerektiğini söylüyor.*