## Veri Standartlaştırma & Değişken Dönüşümü

### Standartlaştırma

In [1]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame(
    {"V1" : V1,
     "V2" : V2,
     "V3" : V3}
)

df = df.astype(float)
df

    V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [2]:
from sklearn import preprocessing

In [3]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

### Normalizasyon

In [4]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

### Min-Max Dönüşümü

In [5]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))

In [6]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

### Binarize Dönüşüm

In [7]:
#Değişken Dönüştürme işlemidir ve bilginin kendisini yapısal olarak etkiler.

In [8]:
binarazer = preprocessing.Binarizer(threshold = 5).fit(df)

In [9]:
binarazer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

### 0-1 Dönüşümü

In [10]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df_l = df.copy()

In [11]:
df_l.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
df_l["yeni_sex"] = df["sex"].cat.codes

In [13]:
df_l.head()

   total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         0
2       21.01  3.50    Male     No  Sun  Dinner     3         0
3       23.68  3.31    Male     No  Sun  Dinner     2         0
4       24.59  3.61  Female     No  Sun  Dinner     4         1

In [14]:
lbe = preprocessing.LabelEncoder()

In [15]:
df_l["daha_yeni_sex"] = lbe.fit_transform(df_l["sex"])

In [16]:
df_l.head()

   total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

### "1 ve Diğerleri"(0) Dönüşümü

In [17]:
#İkiden fazla sınıf bulunduran değişken dönüşümlerinde kullanılır.

In [18]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df_l.head()

   total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

In [20]:
df_l["yeni_gun"] = np.where(df_l["day"].str.contains("Sun"), 1, 0)

In [21]:
df_l.head(20)

,total_bill,tip,sex,smoker,day,time,size,yeni_sex,daha_yeni_sex,yeni_gun
0,16.99,1.01,Female,No,Sun,Dinner,2,1,0,1
1,10.34,1.66,Male,No,Sun,Dinner,3,0,1,1
2,21.01,3.50,Male,No,Sun,Dinner,3,0,1,1
3,23.68,3.31,Male,No,Sun,Dinner,2,0,1,1
4,24.59,3.61,Female,No,Sun,Dinner,4,1,0,1
5,25.29,4.71,Male,No,Sun,Dinner,4,0,1,1
6,8.77,2.00,Male,No,Sun,Dinner,2,0,1,1
7,26.88,3.12,Male,No,Sun,Dinner,4,0,1,1
8,15.04,1.96,Male,No,Sun,Dinner,2,0,1,1
9,14.78,3.23,Male,No,Sun,Dinner,2,0,1,1
10,10.27,1.71,Male,No,Sun,Dinner,2,0,1,1
11,35.26,5.00,Female,No,Sun,Dinner,4,1,0,1
12,15.42,1.57,Male,No,Sun,Dinner,2,0,1,1
13,18.43,3.00,Male,No,Sun,Dinner,4,0,1,1
14,14.83,3.02,Female,No,Sun,Dinner,2,1,0,1
15,21.58,3.92,Male,No,Sun,Dinner,2,0,1,1
16,10.33,1.67,Female,No,Sun,Dinner,3,1,0,1
17,16.29,3.71,Male,No,Sun,Dinner,3,0,1,1
18,16.97,3.50,Female,No,Sun,Dinner,3,1,0,1
19,20.65,3.35,Male,No,Sat,Dinner,3,0,1,0

### Çok Sınıflı Dönüşüm

In [22]:
lbe = preprocessing.LabelEncoder()

In [23]:
df_l["daha_yeni_gun"] = lbe.fit_transform(df_l["day"])

In [24]:
df_l

,total_bill,tip,sex,smoker,day,time,size,yeni_sex,daha_yeni_sex,yeni_gun,daha_yeni_gun
0,16.99,1.01,Female,No,Sun,Dinner,2,1,0,1,2
1,10.34,1.66,Male,No,Sun,Dinner,3,0,1,1,2
2,21.01,3.50,Male,No,Sun,Dinner,3,0,1,1,2
3,23.68,3.31,Male,No,Sun,Dinner,2,0,1,1,2
4,24.59,3.61,Female,No,Sun,Dinner,4,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0,1,0,1
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1,0,0,1
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0,1,0,1
242,17.82,1.75,Male,No,Sat,Dinner,2,0,1,0,1
243,18.78,3.00,Female,No,Thur,Dinner,2,1,0,0,3

### One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [25]:
df_one_hot = df.copy()

In [26]:
#dummy değişken tuzağı
pd.get_dummies(df_one_hot, columns = ["sex"], prefix = ["sex"], dtype = int).head()

   total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

In [27]:
pd.get_dummies(df_one_hot, columns = ["day"], prefix = ["day"], dtype = int).head()

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,0,0,0,1
1,10.34,1.66,Male,No,Dinner,3,0,0,0,1
2,21.01,3.50,Male,No,Dinner,3,0,0,0,1
3,23.68,3.31,Male,No,Dinner,2,0,0,0,1
4,24.59,3.61,Female,No,Dinner,4,0,0,0,1

### Sürekli Değişkeni Kategorik Değişkene Çevirmek

In [28]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
dff = df.select_dtypes(include = ["float64", "int64"])

In [30]:
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], encode = "ordinal", strategy = "quantile").fit(dff)

In [31]:
est.transform(dff)[0 : 10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

### Değişkeni Index'e, Index'i Değişkene Çevirmek

In [32]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [33]:
df["yeni_degisken"] = df.index

In [34]:
df.head()

   total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2              0
1       10.34  1.66    Male     No  Sun  Dinner     3              1
2       21.01  3.50    Male     No  Sun  Dinner     3              2
3       23.68  3.31    Male     No  Sun  Dinner     2              3
4       24.59  3.61  Female     No  Sun  Dinner     4              4

In [35]:
df["yeni_degisken"] = df["yeni_degisken"] + 10

In [36]:
df.head()

   total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2             10
1       10.34  1.66    Male     No  Sun  Dinner     3             11
2       21.01  3.50    Male     No  Sun  Dinner     3             12
3       23.68  3.31    Male     No  Sun  Dinner     2             13
4       24.59  3.61  Female     No  Sun  Dinner     4             14

In [37]:
df.index = df["yeni_degisken"]

In [38]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,yeni_degisken
yeni_degisken,,,,,,,,
10,16.99,1.01,Female,No,Sun,Dinner,2,10
11,10.34,1.66,Male,No,Sun,Dinner,3,11
12,21.01,3.50,Male,No,Sun,Dinner,3,12
13,23.68,3.31,Male,No,Sun,Dinner,2,13
14,24.59,3.61,Female,No,Sun,Dinner,4,14

*Bu Notebook 'Veri Ön İşleme' bölümünün özetini kapsamaktadır.*