## Metin Madenciliği ve Doğal Dil İşleme

### Metin Ön İşleme

In [1]:
import pandas as pd

In [2]:
metin = """
A Scandal in Bohemia! 01
The Red-Headed League,2
A Case, of Identity 33
The Boscombe Valley Mystery4
The Five Orange Pips1
The Man with? the Twisted Lip
The Adventure of the Blue Carbuncle
The Adventure of the Speckled Band
The Adventure of the Engineer's Thumb
The Adventure of the Noble Bachelor
The Adventure of the Beryl Coronet
The Adventure of the Copper Beeches"""

metin

"\nA Scandal in Bohemia! 01\nThe Red-Headed League,2\nA Case, of Identity 33\nThe Boscombe Valley Mystery4\nThe Five Orange Pips1\nThe Man with? the Twisted Lip\nThe Adventure of the Blue Carbuncle\nThe Adventure of the Speckled Band\nThe Adventure of the Engineer's Thumb\nThe Adventure of the Noble Bachelor\nThe Adventure of the Beryl Coronet\nThe Adventure of the Copper Beeches"

In [3]:
#metin verisini düzenlemek || df/array/seri'ye çevirmek

In [4]:
v_metin = metin.split("\n")

In [5]:
v_metin

['',
 'A Scandal in Bohemia! 01',
 'The Red-Headed League,2',
 'A Case, of Identity 33',
 'The Boscombe Valley Mystery4',
 'The Five Orange Pips1',
 'The Man with? the Twisted Lip',
 'The Adventure of the Blue Carbuncle',
 'The Adventure of the Speckled Band',
 "The Adventure of the Engineer's Thumb",
 'The Adventure of the Noble Bachelor',
 'The Adventure of the Beryl Coronet',
 'The Adventure of the Copper Beeches']

In [6]:
v = pd.Series(v_metin)

In [7]:
v

0
1                  A Scandal in Bohemia! 01
2                   The Red-Headed League,2
3                    A Case, of Identity 33
4              The Boscombe Valley Mystery4
5                     The Five Orange Pips1
6             The Man with? the Twisted Lip
7       The Adventure of the Blue Carbuncle
8        The Adventure of the Speckled Band
9     The Adventure of the Engineer's Thumb
10      The Adventure of the Noble Bachelor
11       The Adventure of the Beryl Coronet
12      The Adventure of the Copper Beeches
dtype: object

In [8]:
text_vector = v[1 : len(v)]

In [9]:
text_vector

1                  A Scandal in Bohemia! 01
2                   The Red-Headed League,2
3                    A Case, of Identity 33
4              The Boscombe Valley Mystery4
5                     The Five Orange Pips1
6             The Man with? the Twisted Lip
7       The Adventure of the Blue Carbuncle
8        The Adventure of the Speckled Band
9     The Adventure of the Engineer's Thumb
10      The Adventure of the Noble Bachelor
11       The Adventure of the Beryl Coronet
12      The Adventure of the Copper Beeches
dtype: object

In [10]:
mdf = pd.DataFrame(text_vector, columns = ["stories"])

In [11]:
mdf

                                  stories
1                A Scandal in Bohemia! 01
2                 The Red-Headed League,2
3                  A Case, of Identity 33
4            The Boscombe Valley Mystery4
5                   The Five Orange Pips1
6           The Man with? the Twisted Lip
7     The Adventure of the Blue Carbuncle
8      The Adventure of the Speckled Band
9   The Adventure of the Engineer's Thumb
10    The Adventure of the Noble Bachelor
11     The Adventure of the Beryl Coronet
12    The Adventure of the Copper Beeches

In [12]:
#büyük küçük harf dönüşümü

In [13]:
d_mdf = mdf.copy()

In [14]:
d_mdf

                                  stories
1                A Scandal in Bohemia! 01
2                 The Red-Headed League,2
3                  A Case, of Identity 33
4            The Boscombe Valley Mystery4
5                   The Five Orange Pips1
6           The Man with? the Twisted Lip
7     The Adventure of the Blue Carbuncle
8      The Adventure of the Speckled Band
9   The Adventure of the Engineer's Thumb
10    The Adventure of the Noble Bachelor
11     The Adventure of the Beryl Coronet
12    The Adventure of the Copper Beeches

In [15]:
d_mdf["stories"] = d_mdf["stories"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [16]:
d_mdf

                                  stories
1                a scandal in bohemia! 01
2                 the red-headed league,2
3                  a case, of identity 33
4            the boscombe valley mystery4
5                   the five orange pips1
6           the man with? the twisted lip
7     the adventure of the blue carbuncle
8      the adventure of the speckled band
9   the adventure of the engineer's thumb
10    the adventure of the noble bachelor
11     the adventure of the beryl coronet
12    the adventure of the copper beeches

## Temel String İşlemleri

### Oluşturma, Biçimlendirme

In [17]:
isim = "mcy"

In [18]:
3 * isim

'mcymcymcy'

In [19]:
"mcy" + "ali"

'mcyali'

In [20]:
"K" + isim[1:]

'Kcy'

In [21]:
isimler = ["ali", "veli", "ayse"]

In [22]:
for i in isimler:
    print("İsim:", i, sep  = "")

İsim:ali
İsim:veli
İsim:ayse

In [23]:
for i in isimler:
    print("_", i[0:], sep  = "")

_ali
_veli
_ayse

In [24]:
print(*enumerate(isimler))

(0, 'ali') (1, 'veli') (2, 'ayse')

In [25]:
for i in enumerate(isimler):
    print(i)

(0, 'ali')
(1, 'veli')
(2, 'ayse')

In [26]:
for i in enumerate("isimler"):
    print(i)

(0, 'i')
(1, 's')
(2, 'i')
(3, 'm')
(4, 'l')
(5, 'e')
(6, 'r')

for i in enumerate(isimler, 1):
    print(i)

### Dizi içi Tip Sorgulamaları

In [27]:
"mcy".isalpha()

True

In [28]:
"mcy30".isalpha()

False

In [29]:
"123".isnumeric()

True

In [30]:
"123".isdigit()

True

In [31]:
"123mcy".isalnum()

True

### Elemanlarına ve Eleman Indexlerine Erişmek

In [32]:
isim = "muratcanyaman"

In [33]:
isim

'muratcanyaman'

In [34]:
isim[0:2]

'mu'

In [35]:
isim.index("n")

7

In [36]:
isim.index("a")

3

In [37]:
isim.index("a", 4)

6

### Başlangıç ve Bitiş Karakterlerini Sorgulamak: startswith() & endswith()

In [38]:
isim = "Murat Can Yaman"

In [39]:
isim.startswith("a")

False

In [40]:
isim.startswith("m")

False

In [41]:
isim.startswith("M")

True

In [42]:
isim.endswith("n")

True

In [43]:
#count

In [44]:
isim.count("a")

4

In [45]:
#sorted

In [46]:
sorted("kitap")

['a', 'i', 'k', 'p', 't']

In [47]:
print(*sorted("kalem"), sep = "")

aeklm

### Karakterleri Bölmek

In [48]:
isim = "Murat Can Yaman"

In [49]:
isim.split()

['Murat', 'Can', 'Yaman']

In [50]:
isim.split("a")

['Mur', 't C', 'n Y', 'm', 'n']

In [51]:
isim.split(",")

['Murat Can Yaman']

### Büyük Küçük Harf İşlemleri

In [52]:
isim = "Murat Can Yaman"

In [53]:
isim.upper()

'MURAT CAN YAMAN'

In [54]:
isim.lower()

'murat can yaman'

In [55]:
isim.upper().lower()

'murat can yaman'

In [56]:
isim_b = isim.upper()

In [57]:
isim_b.islower()

False

In [58]:
isim_b.isupper()

True

### capitalize() & title() & swapcase()

In [59]:
isim = "murat can yaman"

In [60]:
isim.capitalize()

'Murat can yaman'

In [61]:
isim.title()

'Murat Can Yaman'

In [62]:
isim = "MURAT can YAMAN"

In [63]:
isim.swapcase()

'murat CAN yaman'

### İstenmeyen Karakterleri Kırpmak: strip(), lstrip(), rstrip()

In [64]:
isim = " murat "

In [65]:
isim.strip()

'murat'

In [66]:
isim = "*murat*"

In [67]:
isim.strip("*")

'murat'

In [68]:
isim.rstrip("*")

'*murat'

In [69]:
isim.lstrip("*")

'murat*'

## join: Bölünmüş İfadelerin Birleştirilmesi

In [70]:
isim = "Murat Can Yaman"

In [71]:
ayrik = isim.split()

In [72]:
ayrik

['Murat', 'Can', 'Yaman']

In [73]:
joiner = " "

In [74]:
joiner.join(ayrik)

'Murat Can Yaman'

### Eleman Değiştirme: replace(), str.maketrans(), translate()

In [75]:
isim = "Kemal"

In [76]:
isim.replace("K", "C")

'Cemal'

In [77]:
ifade = "Bu ifade içerisinde bağzı TÜrkçe karakterler vardır"

In [78]:
duzeltilecek_harfler = "çÇğĞıİöÖşŞüÜ"
duzeltilmis_harfler = "cCgGiIoOsSuU"

In [79]:
alfabe_duzeltme = str.maketrans(duzeltilecek_harfler, duzeltilmis_harfler)

In [80]:
ifade.translate(alfabe_duzeltme)

'Bu ifade icerisinde bagzi TUrkce karakterler vardir'

### contains()

In [81]:
import pandas as pd
isimler = ["ayse", "Ayşe", "ali", "aali", "Ali", "veli", "mehmet", "berkcan"]
v = pd.Series(isimler)

In [82]:
v

0       ayse
1       Ayşe
2        ali
3       aali
4        Ali
5       veli
6     mehmet
7    berkcan
dtype: object

In [83]:
v.str.contains("al")

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [84]:
v[v.str.contains("al")]

2     ali
3    aali
dtype: object

In [85]:
v.str.contains("[Aa]li").sum()

np.int64(3)

### Noktalama İşaretlerinin Silinmesi

In [86]:
d_mdf

                                  stories
1                a scandal in bohemia! 01
2                 the red-headed league,2
3                  a case, of identity 33
4            the boscombe valley mystery4
5                   the five orange pips1
6           the man with? the twisted lip
7     the adventure of the blue carbuncle
8      the adventure of the speckled band
9   the adventure of the engineer's thumb
10    the adventure of the noble bachelor
11     the adventure of the beryl coronet
12    the adventure of the copper beeches

In [87]:
type(d_mdf)

pandas.core.frame.DataFrame

In [88]:
d_mdf["stories"] = d_mdf["stories"].str.replace(r"[^\w\s]", "", regex = True)

In [89]:
d_mdf

                                 stories
1                a scandal in bohemia 01
2                  the redheaded league2
3                  a case of identity 33
4           the boscombe valley mystery4
5                  the five orange pips1
6           the man with the twisted lip
7    the adventure of the blue carbuncle
8     the adventure of the speckled band
9   the adventure of the engineers thumb
10   the adventure of the noble bachelor
11    the adventure of the beryl coronet
12   the adventure of the copper beeches

### Sayıların Silinmesi

In [90]:
d_mdf["stories"] = d_mdf["stories"].str.replace(r"\d","", regex = True)

In [91]:
d_mdf

                                 stories
1                  a scandal in bohemia
2                   the redheaded league
3                    a case of identity
4            the boscombe valley mystery
5                   the five orange pips
6           the man with the twisted lip
7    the adventure of the blue carbuncle
8     the adventure of the speckled band
9   the adventure of the engineers thumb
10   the adventure of the noble bachelor
11    the adventure of the beryl coronet
12   the adventure of the copper beeches

### Stopwords'lerin Silinmesi

In [92]:
import nltk

In [93]:
from nltk.corpus import stopwords

In [94]:
sw = stopwords.words("english")

In [95]:
d_mdf["stories"] = d_mdf["stories"].apply(lambda x: " ".join(x for x in x.split() if x not in sw))

In [96]:
d_mdf

                      stories
1             scandal bohemia
2            redheaded league
3               case identity
4     boscombe valley mystery
5            five orange pips
6             man twisted lip
7    adventure blue carbuncle
8     adventure speckled band
9   adventure engineers thumb
10   adventure noble bachelor
11    adventure beryl coronet
12   adventure copper beeches

### Az geçen kelimelerin silinmesi

In [97]:
type(d_mdf)

pandas.core.frame.DataFrame

In [98]:
pd.Series(" ".join(d_mdf["stories"]).split()).value_counts()

adventure    6
scandal      1
redheaded    1
bohemia      1
case         1
identity     1
boscombe     1
valley       1
mystery      1
five         1
orange       1
league       1
pips         1
man          1
twisted      1
lip          1
blue         1
carbuncle    1
speckled     1
band         1
engineers    1
thumb        1
noble        1
bachelor     1
beryl        1
coronet      1
copper       1
beeches      1
Name: count, dtype: int64

In [99]:
delete = pd.Series(" ".join(d_mdf["stories"]).split()).value_counts()[-3:]

In [100]:
delete

coronet    1
copper     1
beeches    1
Name: count, dtype: int64

In [101]:
d_mdf["stories"] = d_mdf["stories"].apply(lambda x: " ".join(x for x in x.split() if x not in delete))

In [102]:
d_mdf

                      stories
1             scandal bohemia
2            redheaded league
3               case identity
4     boscombe valley mystery
5            five orange pips
6             man twisted lip
7    adventure blue carbuncle
8     adventure speckled band
9   adventure engineers thumb
10   adventure noble bachelor
11            adventure beryl
12                  adventure

### Tokenization

In [103]:
import textblob

In [104]:
from textblob import TextBlob

In [105]:
d_mdf["stories"] = d_mdf["stories"].apply(lambda x: TextBlob(x).words)

In [106]:
d_mdf

                          stories
1              [scandal, bohemia]
2             [redheaded, league]
3                [case, identity]
4     [boscombe, valley, mystery]
5            [five, orange, pips]
6             [man, twisted, lip]
7    [adventure, blue, carbuncle]
8     [adventure, speckled, band]
9   [adventure, engineers, thumb]
10   [adventure, noble, bachelor]
11             [adventure, beryl]
12                    [adventure]

### Stemming

In [107]:
from nltk.stem import PorterStemmer

In [108]:
st = PorterStemmer()

In [109]:
d_mdf["stories"].apply(
    lambda x: " ".join(st.stem(i) for i in x)
)

1            scandal bohemia
2              redhead leagu
3                 case ident
4     boscomb valley mysteri
5             five orang pip
6              man twist lip
7     adventur blue carbuncl
8       adventur speckl band
9       adventur engin thumb
10    adventur nobl bachelor
11            adventur beryl
12                  adventur
Name: stories, dtype: object

### Lemmatization

In [110]:
from textblob import Word

In [111]:
d_mdf["stories"] = d_mdf["stories"].apply(lambda x: " ".join(Word(word).lemmatize() for word in x))

In [112]:
mdf["stories"][1:5]

2         The Red-Headed League,2
3          A Case, of Identity 33
4    The Boscombe Valley Mystery4
5           The Five Orange Pips1
Name: stories, dtype: object

In [113]:
d_mdf["stories"][1:5]

2           redheaded league
3              case identity
4    boscombe valley mystery
5            five orange pip
Name: stories, dtype: object

## NLP Uygulamaları

### N-Gram

In [114]:
from textblob import TextBlob

In [115]:
text = """Bu örneği anlaşılabilmesi için daha uzun bir metin üzerinden göstereceğim.
N-gram'lar birlikte kullanılan kelimelerin kombinasyonlarını gösterir"""

In [116]:
TextBlob(text).ngrams(3)

[WordList(['Bu', 'örneği', 'anlaşılabilmesi']),
 WordList(['örneği', 'anlaşılabilmesi', 'için']),
 WordList(['anlaşılabilmesi', 'için', 'daha']),
 WordList(['için', 'daha', 'uzun']),
 WordList(['daha', 'uzun', 'bir']),
 WordList(['uzun', 'bir', 'metin']),
 WordList(['bir', 'metin', 'üzerinden']),
 WordList(['metin', 'üzerinden', 'göstereceğim']),
 WordList(['üzerinden', 'göstereceğim', "N-gram'lar"]),
 WordList(['göstereceğim', "N-gram'lar", 'birlikte']),
 WordList(["N-gram'lar", 'birlikte', 'kullanılan']),
 WordList(['birlikte', 'kullanılan', 'kelimelerin']),
 WordList(['kullanılan', 'kelimelerin', 'kombinasyonlarını']),
 WordList(['kelimelerin', 'kombinasyonlarını', 'gösterir'])]

### Part of Speech Tagging (POS)

In [117]:
import nltk

In [118]:
d_mdf

                     stories
1            scandal bohemia
2           redheaded league
3              case identity
4    boscombe valley mystery
5            five orange pip
6            man twisted lip
7   adventure blue carbuncle
8    adventure speckled band
9   adventure engineer thumb
10  adventure noble bachelor
11           adventure beryl
12                 adventure

In [119]:
TextBlob(d_mdf["stories"][2]).tags

[('redheaded', 'VBN'), ('league', 'NN')]

In [120]:
d_mdf["stories"].apply(lambda x: TextBlob(x).tags)

1                     [(scandal, NN), (bohemia, NN)]
2                   [(redheaded, VBN), (league, NN)]
3                       [(case, NN), (identity, NN)]
4      [(boscombe, NN), (valley, NN), (mystery, NN)]
5              [(five, CD), (orange, NN), (pip, NN)]
6             [(man, NN), (twisted, VBD), (lip, NN)]
7     [(adventure, NN), (blue, JJ), (carbuncle, NN)]
8     [(adventure, NN), (speckled, VBD), (band, NN)]
9     [(adventure, NN), (engineer, NN), (thumb, NN)]
10    [(adventure, NN), (noble, JJ), (bachelor, NN)]
11                    [(adventure, NN), (beryl, NN)]
12                                 [(adventure, NN)]
Name: stories, dtype: object

### Chunking (shallow parsing)

In [121]:
sentence = "R and Python are useful data science tools for the new or old data scientists who eager to do efficent data science task."

In [122]:
pos = TextBlob(sentence).tags

In [123]:
pos

[('R', 'NNP'),
 ('and', 'CC'),
 ('Python', 'NNP'),
 ('are', 'VBP'),
 ('useful', 'JJ'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('tools', 'NNS'),
 ('for', 'IN'),
 ('the', 'DT'),
 ('new', 'JJ'),
 ('or', 'CC'),
 ('old', 'JJ'),
 ('data', 'NNS'),
 ('scientists', 'NNS'),
 ('who', 'WP'),
 ('eager', 'VBP'),
 ('to', 'TO'),
 ('do', 'VB'),
 ('efficent', 'JJ'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('task', 'NN')]

In [124]:
reg_exp = "NP: {<DT>?<JJ>*<NN>}"
rp = nltk.RegexpParser(reg_exp)

In [125]:
results = rp.parse(pos)

In [126]:
print(results)

(S
  R/NNP
  and/CC
  Python/NNP
  are/VBP
  useful/JJ
  data/NNS
  (NP science/NN)
  tools/NNS
  for/IN
  the/DT
  new/JJ
  or/CC
  old/JJ
  data/NNS
  scientists/NNS
  who/WP
  eager/VBP
  to/TO
  do/VB
  efficent/JJ
  data/NNS
  (NP science/NN)
  (NP task/NN))

In [127]:
results.draw()

### Named Entity Recognation

In [128]:
from nltk import word_tokenize, pos_tag, ne_chunk

In [129]:
sentence = "Hadley is creative people who work for R Studio AND he attented conference at Newyork last year."

In [130]:
print(ne_chunk(pos_tag(word_tokenize(sentence))))

(S
  (GPE Hadley/NNP)
  is/VBZ
  creative/JJ
  people/NNS
  who/WP
  work/VBP
  for/IN
  (ORGANIZATION R/NNP Studio/NNP)
  AND/CC
  he/PRP
  attented/VBD
  conference/NN
  at/IN
  (ORGANIZATION Newyork/NNP)
  last/JJ
  year/NN
  ./.)

## Matematiksel İşlemler ve Basit Özellik Çıkarımı

In [131]:
d_mdf["stories"]

1              scandal bohemia
2             redheaded league
3                case identity
4      boscombe valley mystery
5              five orange pip
6              man twisted lip
7     adventure blue carbuncle
8      adventure speckled band
9     adventure engineer thumb
10    adventure noble bachelor
11             adventure beryl
12                   adventure
Name: stories, dtype: object

### Harf/Karakter Sayısı

In [132]:
o_mdf = d_mdf.copy()

In [133]:
o_mdf["letter_count"] = d_mdf["stories"].str.len()

In [134]:
o_mdf

                     stories  letter_count
1            scandal bohemia            15
2           redheaded league            16
3              case identity            13
4    boscombe valley mystery            23
5            five orange pip            15
6            man twisted lip            15
7   adventure blue carbuncle            24
8    adventure speckled band            23
9   adventure engineer thumb            24
10  adventure noble bachelor            24
11           adventure beryl            15
12                 adventure             9

### Kelime Sayısı

In [135]:
o_mdf["word_count"] = o_mdf["stories"].apply(lambda x: len(str(x).split(" ")))

In [136]:
o_mdf

                     stories  letter_count  word_count
1            scandal bohemia            15           2
2           redheaded league            16           2
3              case identity            13           2
4    boscombe valley mystery            23           3
5            five orange pip            15           3
6            man twisted lip            15           3
7   adventure blue carbuncle            24           3
8    adventure speckled band            23           3
9   adventure engineer thumb            24           3
10  adventure noble bachelor            24           3
11           adventure beryl            15           2
12                 adventure             9           1

### Özel Karakterleri Yakalamak & Saydırmak

In [137]:
o_mdf["char_count"] = o_mdf["stories"].apply(lambda x: len([x for x in x.split()
                                      if x.startswith("adventure")]))

In [138]:
o_mdf

                     stories  letter_count  word_count  char_count
1            scandal bohemia            15           2           0
2           redheaded league            16           2           0
3              case identity            13           2           0
4    boscombe valley mystery            23           3           0
5            five orange pip            15           3           0
6            man twisted lip            15           3           0
7   adventure blue carbuncle            24           3           1
8    adventure speckled band            23           3           1
9   adventure engineer thumb            24           3           1
10  adventure noble bachelor            24           3           1
11           adventure beryl            15           2           1
12                 adventure             9           1           1

### Sayıları Yakalamak & Saydırmak

In [139]:
mdf["stories"].apply(lambda x: len([x for x in x.split()
                                      if x.isdigit()]))

1     1
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
Name: stories, dtype: int64